
DELIMITER $ 

/* STORED PROCEDURE */ 

CREATE PROCEDURE NOME()
BEGIN

    QUALQUER PROGRMAÇÃO;  -- PRECISA MUDAR O DELIMITAR PARA QUE SE IGNORE O ";"
END
$

CREATE PROCEDURE NOME_EMPRESA()
BEGIN

    SELECT 'UNIVERSIDADE DOS DADOS' AS EMPRESA;
END
$

CALL NOME_MPRESA()$

CREATE PROCEDURE CONTA(NUMERO1 AS INT, NUMERO2 AS INT)
BEGIN

        SELECT NUMERO1 + NUMERO2 AS CONTA;

END
$

DROP PROCEDURE CONTA;



CREATE PROCEDURE CONTA(NUMERO1 AS INT, NUMERO2 AS INT)
BEGIN

        SELECT NUMERO1 + NUMERO2 AS CONTA;

END
$

CALL CONTA(100, 50)


CREATE DATABASE PROJETO;

USE PROJETO;

CREATE TABLE CURSOS(
	IDCURSO INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30) NOT NULL,
	HORAS INT(3) NOT NULL,
	VALOR FLOAT(10,2) NOT NULL
);

INSERT INTO CURSOS VALUES(NULL,'JAVA',30,500.00);
INSERT INTO CURSOS VALUES(NULL,'FUNDAMENTOS DE BANCOS DE DADOS',40,700.00);


-- INSERINDO DADOS NAS TABELAS

DELIMITER #

CREATE PROCEDURE CAD_CURSO(P_NOME VARCHAR(30), P_HORAS INT (3), P_PRECO FLOAT(10, 2))
BEGIN

    INSERT INTO CURSOS VALUES(NULL, P_NOME, P_HORAS, P_PRECO);

END
#

DELIMITER ;

CALL CAD_CURSO('BI_SQL_SERVER', 35, 3000.00);

-- PROCEDURE PARA CONSULTAR CURSOS
