
/* VENDEDOR QUE MENOS VENDEU EM MARÇO E SEU NOME */ 

SELECT 
    NOME,
    MARCO AS VALOR
FROM VENDEDORES
WHERE 1 = 1
    AND MARCO = (SELECT MIN(MARCO) FROM VENDEDORES);



/* VENDEDOR QUE MAIS VENDEU EM MARÇO E SEU NOME */ 

SELECT 
    NOME,
    MARCO AS VALOR
FROM VENDEDORES
WHERE 1 = 1
    AND MARCO = (SELECT MAX(MARCO) FROM VENDEDORES);

    
/* VENDEDORES QUE VENDERAM MAIS QUE A MÉDIA EM FEVEREIRO E SEU NOME */

SELECT 
    NOME,
    FEVEREIRO AS VALOR
FROM VENDEDORES
WHERE 1 = 1
    AND FEVEREIRO > (SELECT AVG(FEVEREIRO) FROM VENDEDORES);


/* TOTAL POR LINHA */
SELECT
    JANEIRO,
    FEVEREIRO,
    MARCO,
    (JANEIRO + FEVEREIRO + MARCO) AS TOTAL
FROM VENDEDORES;
