
CREATE DATABASE COMERCIO;

USE COMERCIO;

CREATE TABLE CLIENTE (
    ID_CLIENTE INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(30) NOT NULL,
    SEXO ENUM('M', 'F') NOT NULL,
    EMAIL VARCHAR(50) UNIQUE,
    CPR VARCHAR(15) UNIQUE
);

CREATE TABLE ENDERECO (
    ID_ENDERECO INT PRIMARY KEY AUTO_INCREMENT,
    RUA VARCHAR(30) NOT NULL,
    BAIRRO VARCHAR(30)  NOT NULL,
    CIDADE VARCHAR(30) NOT NULL,
    ESTADO CHAR(2) NOT NULL,
    ID_CLIENTE INT UNIQUE,
    FOREIGN KEY (ID_CLIENTE)
    REFERENCES CLIENTE(ID_CLIENTE)
);

CREATE TABLE TELEFONE (
    ID_TELEFONE INT PRIMARY KEY AUTO_INCREMENT,
    TIPO ENUM('RES', 'COM', 'CEL') NOT NULL,
    NUMERO VARCHAR(10) NOT NULL,
    ID_CLIENTE INT,
    FOREIGN KEY (ID_CLIENTE)
    REFERENCES CLIENTE(ID_CLIENTE)
);



-- INSERINDO DADOS
INSERT INTO CLIENTE VALUES (NULL, 'JOAO',   'M',    'JOAO@IG.COM',          '18283712873');
INSERT INTO CLIENTE VALUES (NULL, 'CARLOS', 'M',    'CARLOS@TERRA.COM',     '13212331231');
INSERT INTO CLIENTE VALUES (NULL, 'ANA',    'F',    'ANA@IG.COM',           '61535313651');
INSERT INTO CLIENTE VALUES (NULL, 'CLARA',  'F',    NULL,                   '15137676445');
INSERT INTO CLIENTE VALUES (NULL, 'JORGE',  'M',    'JJ@GMAIL.COM',         '45762725472');
INSERT INTO CLIENTE VALUES (NULL, 'CELIA',  'F',    'CELIAA@OUTLOOK.COM',   '18283712873');

INSERT INTO ENDERECO VALUES (NULL, 'RUA ANTONIO DA',        'CENTRO',   'B. HORIZONTE',     'MG', 4);
INSERT INTO ENDERECO VALUES (NULL, 'RUA CAPITAO HERMES',    'CENTRO',   'RIO DE JANEIRO',   'RJ', 1);
INSERT INTO ENDERECO VALUES (NULL, 'RUA PRES VARGAS',       'JARDINS',  'B. HORIZONTE',     'MG', 3);
INSERT INTO ENDERECO VALUES (NULL, 'RUA ALFANDEGA',         'ESTACIO',  'RIO DE JANEIRO',   'RJ', 2);
INSERT INTO ENDERECO VALUES (NULL, 'RUA DO OUVIDOR',        'FLAMENGO', 'RIO DE JANEIRO',   'RJ', 6);
INSERT INTO ENDERECO VALUES (NULL, 'RUA URUGUAIANA',        'CENTRO',   'VITORIA',          'ES', 5);
INSERT INTO ENDERECO VALUES (NULL, 'RUA ALFANDEGA',         'CENTRO',   'SAO PAULO',        'SP', 5);

INSERT INTO TELEFONE VALUES (NULL,'CEL','78458743',5);
INSERT INTO TELEFONE VALUES (NULL,'RES','56576876',5);
INSERT INTO TELEFONE VALUES (NULL,'CEL','87866896',1);
INSERT INTO TELEFONE VALUES (NULL,'COM','54768899',2);
INSERT INTO TELEFONE VALUES (NULL,'RES','99667587',1);
INSERT INTO TELEFONE VALUES (NULL,'CEL','78989765',3);
INSERT INTO TELEFONE VALUES (NULL,'CEL','99766676',3);
INSERT INTO TELEFONE VALUES (NULL,'COM','66687899',1);
INSERT INTO TELEFONE VALUES (NULL,'RES','89986668',5);
INSERT INTO TELEFONE VALUES (NULL,'CEL','88687909',2);