SELECT TIPO, NUMERO FROM TELEFONE;

SELECT NOW() AS DATA_ATUAL;
SELECT 2 + 2 AS SOMA;
SELECT 2 + 2 AS SOMA, NOME, NOW() FROM CLIENTE;

SELECT -- PROJEÇÃO
    C.ID_CLIENTE, 
    C.CPR, 
    C.NOME, 
    T.NUMERO, 
    C.EMAIL, 
    E.RUA, 
    E.BAIRRO, 
    E.CIDADE, 
    E.ESTADO
FROM
    CLIENTE C
INNER JOIN ENDERECO E ON C.ID_CLIENTE = E.ID_CLIENTE
LEFT JOIN TELEFONE T ON C.ID_CLIENTE = T.ID_CLIENTE
WHERE
    C.SEXO = 'M'; -- SELEÇÃO


/*
    DML - DATA MANIPULATION LANGUAGE
    DDL - DATA DEFINITION LANGUAGE
    DCL - DATA CONTROL LANGUAGE
    TCL - TRANSACTION CONTROL LANGUAGE
*/

INSERT INTO CLIENTE VALUES(NULL,'PAULA','M',NULL,'77437493');
INSERT INTO ENDERECO VALUES(NULL,'RUA JOAQUIM SILVA','ALVORADA','NITEROI', 'RJ',7);

SELECT * FROM CLIENTE WHERE ID_CLIENTE = 7;
UPDATE CLIENTE
SET SEXO = 'F' 
WHERE ID_CLIENTE = 7;


/* 
  DDL - DATA DEFINITION LANGUAGE
*/
CREATE TABLE PRODUTO(
	IDPRODUTO INT PRIMARY KEY AUTO_INCREMENT,
	NOME_PRODUTO VARCHAR(30) NOT NULL,
	PRECO INT,
	FRETE FLOAT(10,2) NOT NULL
);

/* ALTERANDO O NOME DE UMA COLUNA - CHANGE */
ALTER TABLE PRODUTO
CHANGE PRECO VALOR_UNITARIO INT NOT NULL;

/* MODIFY - ALTERANDO O TIPO */
ALTER TABLE PRODUTO
MODIFY VALOR_UNITARIO VARCHAR(50) NOT NULL;

/* ADICIONANDO COLUNAS */
ALTER TABLE PRODUTO
ADD PESO FLOAT(10,2) NOT NULL;

/* APAGANDO UMA COLUNA */
ALTER TABLE PRODUTO
DROP COLUMN PESO;

/* ADICIONANDO UMA COLUNA NA ORDEM ESPECIFICA */
ALTER TABLE PRODUTO
ADD COLUMN PESO FLOAT(10,2) NOT NULL
AFTER NOME_PRODUTO;

ALTER TABLE PRODUTO
DROP COLUMN PESO;

ALTER TABLE PRODUTO
ADD COLUMN PESO FLOAT(10,2) NOT NULL
FIRST;