
-- FUNÇÕES: IFNULL()
SELECT  C.NOME, 
		IFNULL(C.EMAIL,'NAO TEM EMAIL'), 
		E.ESTADO, 
		T.NUMERO
FROM CLIENTE C
INNER JOIN ENDERECO E
ON C.IDCLIENTE = E.ID_CLIENTE
INNER JOIN TELEFONE T
ON C.IDCLIENTE = T.ID_CLIENTE;

/* VIEW */
 
CREATE VIEW V_RELATORIO AS 
SELECT 
	C.NOME,
	C.SEXO,
	C.EMAIL,
	T.TIPO,
	T.NUMERO,
	E.BAIRRO,
	E.CIDADE,
	E.ESTADO
FROM CLIENTE C
INNER JOIN TELEFONE T 
	ON C.IDCLIENTE = T.ID_CLIENTE
INNER JOIN ENDERECO E
	ON C.IDCLIENTE = E.ID_CLIENTE

SELECT * FROM RELATORIO;

SHOW TABLES;

-- APAGANDO UMA VIEW
DROP VIEW RELATORIO;



/* ORDER BY */
CREATE TABLE ALUNOS(
	NUMERO INT,
	NOME VARCHAR(30)
);
INSERT INTO ALUNOS VALUES(1,'JOAO');
INSERT INTO ALUNOS VALUES(1,'MARIA');
INSERT INTO ALUNOS VALUES(2,'ZOE');
INSERT INTO ALUNOS VALUES(2,'ANDRE');
INSERT INTO ALUNOS VALUES(3,'CLARA');
INSERT INTO ALUNOS VALUES(1,'CLARA');
INSERT INTO ALUNOS VALUES(4,'MAFRA');
INSERT INTO ALUNOS VALUES(5,'JANAINA');
INSERT INTO ALUNOS VALUES(1,'JANAINA');
INSERT INTO ALUNOS VALUES(3,'MARCELO');
INSERT INTO ALUNOS VALUES(4,'GIOVANI');
INSERT INTO ALUNOS VALUES(5,'ANTONIO');
INSERT INTO ALUNOS VALUES(6,'ANA');
INSERT INTO ALUNOS VALUES(6,'VIVIANE'); 

SELECT * 
FROM ALUNOS
ORDER BY NUMERO

SELECT * 
FROM ALUNOS
ORDER BY 2